MAX_DUPES_IN_PILE = 4
GRID_LENGTH_X = 160
GRID_LENGTH_Y = 90
FPS = 30 #frames per second
SCREEN_WITH = 1920
SCREEN_HEIGHT = 1080
SCREEN_SIZE=(SCREEN_WITH,SCREEN_HEIGHT)
CAPTION = "Unicorn competition"
